apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: "word-count-minio-{{ ts_nodash }}-{{ run_id | replace(':','-') }}"
  namespace: spark-job
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "spark-minio-s3a-custom:3.5.0"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "s3a://spark-jobs/test_spark_job.py"
  sparkVersion: "3.5.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 2
    onFailureRetryInterval: 10
  sparkConf:
    "spark.hadoop.fs.s3a.endpoint": "http://minio-service.minio.svc.cluster.local:9000"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.connection.ssl.enabled": "false"
    "spark.hadoop.fs.s3a.aws.credentials.provider": "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    "spark.hadoop.fs.s3a.access.key": "minio-admin"
    "spark.hadoop.fs.s3a.secret.key": "minio-secret-password"
    "spark.sql.shuffle.partitions": "2"
    "spark.sql.adaptive.enabled": "true"
    "spark.eventLog.enabled": "false"
    "spark.driver.extraClassPath": "/opt/spark/jars/*"
    "spark.executor.extraClassPath": "/opt/spark/jars/*"
  driver:
    cores: 1
    memory: "512m"
    serviceAccount: spark-driver-sa
  executor:
    cores: 1
    instances: 1
    memory: "512m"