---
apiVersion: v1
kind: Secret
metadata:
  name: minio-spark-connect-secret
  namespace: spark-connect
  labels:
    app: spark
type: Opaque
data:
  access-key: bWluaW8tYWRtaW4= 
  secret-key: bWluaW8tc2VjcmV0LXBhc3N3b3Jk
